on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main
  pull_request:

jobs:
  check:
    runs-on: ubuntu-24.04

    name: Types and Linting
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up UV
        uses: astral-sh/setup-uv@9ad030384d649dcdad575ef964e02a9fdce218ab  # ~v5.4.1
        with:
          enable-cache: true
          cache-dependency-glob: |
            pyproject.toml
            uv.lock

      - name: Set up Node for Pyright
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020  # ~v4.3.0
        with:
          node-version-file: .node-version

      - name: Check Types and Linting
        run: >
          uv run --frozen check.py
