on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [opened, reopened, synchronize]

jobs:
  check:
    runs-on: ubuntu-22.04

    name: Types and Linting
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up UV
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: |
            pyproject.toml
            uv.lock

      - name: Set up Node for Pyright
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Check Types and Linting
        run: >
          uv run --frozen check.py

      - name: Verify No CLRF line endings
        run: >
          ! $(find . ! -path "./.git/*" -not -type d -exec file "{}" ";" |& grep -q " CRLF ")
