on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main
  pull_request:

jobs:
  check:
    runs-on: ubuntu-24.04

    name: Types and Linting
    steps:
      - uses: actions/checkout@v5

      - uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39  # v8.2.0
        with:
          enable-cache: true
          cache-python: true

      - run: uv run check.py
